### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by gbrigens** [morrismukiri/Dairy#1]
Can you provide me with one password for the employee to test it? I have tried creating one from phpmyadmin but  not working maybe the hash function.

**Comment by morrismukiri** [comment]
You're right, this could use an update and a better documentation. The hash function is a simple md5 though.

**Comment by gbrigens** [comment]
I like the way you've structured your code, nice one.

**Comment by gbrigens** [comment]
Also it doesn't give error when you enter a wrong password it just loops to the same login page, am really interested in looking how it works, I won't mind if you could share a password like for one account to try it out.

**Comment by morrismukiri** [comment]
I've added the accounts and some basic howro in the readme

**Comment by gbrigens** [comment]
I decrypted the password online and i was able to view the system, nice work.You specialize on php? I have been working on php for backend but am shifting to JS frameworks at the moment am learning angular2 and Meteor. JS is is the future and you can kill to birds or even more on this case haha. develop mobile application and web application that are so interactive. Coz I have been struggling with so many languages :(, but with framework like angular2 I can develop apps for desktop(using electron), web and mobile(Using Ionic) for both platforms.
